# git-credential-cache: Deroffing man parser
# Autogenerated from man pages
complete -c git-credential-cache -l timeout --description 'Number of seconds to cache credentials (defau... [See Man Page]'
complete -c git-credential-cache -l socket --description 'Use <path> to contact a running cache daemon ... [See Man Page]'

