# memcapable: Deroffing man parser
# Autogenerated from man pages
complete -c memcapable -s h
complete -c memcapable -s p
complete -c memcapable -s c
complete -c memcapable -s v
complete -c memcapable -s t --description 'Set the timeout from an IO operation to/from ... [See Man Page]'

