# xtrap: Deroffing man parser
# Autogenerated from man pages
complete -c xtrap -o 'd[isplay]' --description 'Specifies the server to record from or playba... [See Man Page]'
complete -c xtrap -s e --description 'Record only (and all) events'
complete -c xtrap -s f --description 'The pathname of the script to be recorded / p... [See Man Page]'
complete -c xtrap -s v --description 'Verbose mode'

